language: python
sudo: true

env:


before_install:
  - # Do nothing.
  - sudo luarocks install luacov-coveralls

install:
  - # Do nothing. 
  luarocks install https://luarocks.org/manifests/olivine-labs/busted-2.0.rc11-0.rockspec

script:
  /bin/sh .travis/check_lua.sh ${TRAVIS_BUILD_DIR}/check.sh

after_success:
  - luacov-coveralls

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: alway
