language: python
sudo: true

env:


before_install:
  - # Do nothing.

install:
  - # Do nothing. 

script:
  /bin/sh .travis/check_lua.sh ${TRAVIS_BUILD_DIR}/check.sh

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: alway
