language: python
sudo: true

env:

before_install:
  - # Do nothing.
  - source .travis/install_luarocks.sh

install:
  - # Do nothing. 
  - sudo luarocks install luacov-coveralls

script:
  /bin/sh ${TRAVIS_BUILD_DIR}/.travis/check_lua.sh ${TRAVIS_BUILD_DIR}/check.sh
  /bin/sh ${TRAVIS_BUILD_DIR}/.travis/coverage.sh ${TRAVIS_BUILD_DIR}/coverage.sh

after_success:
  - luacov-coveralls

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: alway
