language: python
sudo: true

env:


before_install:
  - source .travis/setup_lua.sh

install:
  - # Do nothing. 

script:
  - # Do nothing. 

branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: alway

