language: python
sudo: true

env:


before_install:
  - source .travis/setenv_lua.sh

install:

script:

after_success:


branches:
  except:
    - gh-pages

notifications:
  email:
    on_success: change
    on_failure: alway
