# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# on: [push, pull_request]
on:
  workflow_dispatch:
  repository_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        luaVersion: ["5.1.5", "5.2.4", "5.3.5", "5.4.0", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1", "5.4"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
      
    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - name: install luarocks
      uses: leafo/gh-actions-luarocks@v2
      
    - name: install luacov
      run: |
        luarocks install luacov
      if: success()
      
    - name: Run UnitTest
      run: |
        bash ${GITHUB_WORKSPACE}/unittest.sh lua ${GITHUB_WORKSPACE}
      shell: bash
      if: success()

